# Generated by Django 3.0.7 on 2020-06-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
