# Generated by Django 3.0.7 on 2020-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_member_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
