# Generated by Django 3.0.7 on 2020-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='flyer',
        ),
    ]
