# Generated by Django 3.0.7 on 2020-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_event_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='event',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
