# Generated by Django 3.0.7 on 2020-06-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200612_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
