# Generated by Django 3.0.7 on 2020-06-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200612_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Toot',
        ),
    ]
