# Generated by Django 3.0.7 on 2020-06-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200613_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toot',
        ),
    ]
