# Generated by Django 3.0.7 on 2020-06-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_delete_toot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('main_5', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
