# Generated by Django 3.0.7 on 2020-06-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
