# Generated by Django 3.0.7 on 2020-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
                ('url', models.URLField(blank=True, null=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Major', models.CharField(max_length=200)),
                ('An_Eboard', models.BooleanField(default=False)),
                ('Position', models.BooleanField(default=False)),
                ('Alumni', models.BooleanField(default=False)),
                ('Term', models.CharField(max_length=100)),
            ],
        ),
    ]
