# Generated by Django 3.0.7 on 2020-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='An_Eboard',
        ),
        migrations.AddField(
            model_name='member',
            name='Eboard',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='Alumni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='Position',
            field=models.CharField(max_length=100),
        ),
    ]
