# Generated by Django 3.0.7 on 2020-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200610_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Alumni',
            new_name='alumni',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Eboard',
            new_name='eboard',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Major',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Term',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='nikname', max_length=15),
        ),
    ]
