# Generated by Django 3.0.7 on 2020-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200611_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
