# Generated by Django 3.0.7 on 2020-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200611_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='alumni',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='eboard',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
