# Generated by Django 3.0.7 on 2020-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
