# Generated by Django 3.0.7 on 2020-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200611_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
