# Generated by Django 3.0.7 on 2020-06-11 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200611_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
