# Generated by Django 3.0.7 on 2020-06-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200611_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
