# Generated by Django 3.0.7 on 2020-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
