# Generated by Django 3.0.7 on 2020-06-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_toot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toot',
        ),
    ]
